print("     			  `/+o/.")
print("                       .+sso+/:oydyo/:-:+shdys/    `-:.     `-/+o+/`")
print("                 `/sdh+/::/::ss:`ymdhyso//hmMNyhNNms+ososys+/-:/shms/`")
print("                .+hNNy++oo+/.`.--/osyhdmNNMMMMMMMMMNdsssssoso+hhhhsoo+ymdo.")
print("              -smNy/+ymmmmmNNNNMNMMMMMNNNmmNMMMMMMMMMho:///:--shydNMMNdo-sNs`")
print("            -hNd+-sNMNdmNMMMNNNMNNNMMMddNMMNNmNMMMMMMNmy+///::/:-:/++ymNNdmMN:")
print("          `sNMs`+NMNNNMMMMNNNMMMMMMNmhyso///+ohMmoNMmoo+/::/-:oymNNmsosshdhmMM/")
print("         +NMMy`hMMMhyNMNMMNNNMds:-.`-:syddmNMMmyo`+yMMho:..-+//++omMNNNNNNNmdNMs")
print("       :mMMMh`yMNdodNNNMNMMMs.+sdmmmmmdhNMMMNhy/..`-syhNmdyssso+/.`:yNMMMMNMNMMMy")
print("      :NMNh:-+MMh+mdNNNNNMd.+NNMMMMMMMMmho:-......:--::ohNMMMMMMNmNy/.oNMNmNMNMMMs")
print("     :NMm+/dmmMNydyhNdhMMN.yMMNmhysso+:-``        ```.--:/+sdMMMMMNNNm:-mMNNNNMMMMy")
print("    :NMy/hNMMMMmNddsh/NmMy-Mms:..`.--.`                ``..-.:yNMMMMNMNs:NMMMNNNNMMy")
print("   :NNy/mMMMMMMmNMMshsNdMo/d-...``                       ```...-yMMMNNMd`NMMNMdmoNMM-")
print("  /mMm+NMNNMMNMNNNNNNNNMMmom/                              ```..`+NMMMMh`NMMMMNNdhNMh")
print(" +NMMmmMNyNMNMMMMMNmmmNMdNNyh+.                             ``````/NMMM::MMMMNMNNmNMN")
print("+MNNMMMNymMNNMMMNNNNNMh+:+dNmddhyoo+`                        ````.`sMMN`sMNNMNNMNNNNN")
print("dNNNMNNddMNNNNNNmymMN+---::/shdhyyy:                         `````..hMo.NMNMNMMMNmMMd")
print("dNNNMMNmNNNmmNMNdNMM+.-..----.-:::.                          ````...:mh/NMMMNMMMNNMMh")
print("sMNNMMNMNNmyNMNdmNMo--.....                                  ``...---:dNMNMMNMMNNNMMN.")
print(":NNNMMMNNNsmMNmMNMy...`.-.`                                    `.-----:odNmmNMMMMMNMMo")
print(".NMMMmMMMNmMNNNNMm:-.```..                                       ``-----:/o//dMMMNMMMm")
print(".NMMMNMMNMMNMNNNNs--.``...                                         `....---..dMNMMMMM`")
print(".NNMMNNNNNMMMNNNN:-...`...                                          ```.....`+MMMMMMM.")
print(".MNNNNNNNMMMMMNNy.......-.`                                         ``..---.`.NMMMMMM`")
print("`NMNMMNNNMMNMMMm-...`.-----.`                                        ``.-----.`yMMMMMd")
print(" dMMMNNNNMMNNMMo`-....----..`          ``                      `.`` ```.------`:MMMMM-")
print(" /MMNMNNNMMNMMN-`.`..-.--.` `--..-:-.-.``..``               ```.-......--.----..NMMMd")
print(" `mMNMNNMMMNNMN.``...-.-../hddyysyhysyyso+--/::-..--...----:::+syyyyhhdddy+:-.-.hMMM:")
print("  :NNNNNNMMMMMN.`....--.:dy/:-.-/+++ososss+/:+shyo/::/:+os+:+syosyoso+/://ss//.`+MMm")
print("   +MdmNNMNMMMN+.--....:+-.-:+ooymdddmdhyo++ss+/yMo.`..oNsyhdhmdmmmmNmdo:-.--:+-:MM/")
print("  `y/..-+dNNMMMo-shhyo++--+sso-`dsymoso.smyso+//.od+/:/ho+yyhd/ymsNhyy./yy/``.-hhmm`")
print("  .s+md+- oMMMm``.-/sy//-.+/s.  odys+s-  /shyso+.sm+:::yd/hh+:`.hyyhy- `/y/.` `hs/s`")
print("  -oyMNyhs:NMMo     `.-`         .---` ``.`/::+s/ms````-mo+:`````.--` ````     `sNm`")
print("  `hsMh`.hymMM:       `-         `          .:+:hy`     od:-`                  .+sM-``")
print("   o+o/``-/mMM-        .-                ``.```hy`       s.`.`                 -/+M+``")
print("   .s `./NMMMM-         --            ````  `:ho`        .s`  ```             ./.+My`")
print("    /: `+MMdMM/          -.  `       `   ..+++-           :d/.             ``:o-`oMy")
print("     o. .sdNMMm`            `--:://+//.`-///:.           `.ohooo:-.`` `.-:+//:..`hMy")
print("     `s```.yMMMs                  ```     .y+  `::.:----.-``o:-::/:::--:::-----..mMo")
print("      :s` `oMNMN-                         :N+  -NNhy/:/sds./:..----------------`/MN")
print("        +o``-NMNMd`                      `-syyoo++/.++:so/+yN+..--....-..-....--`dM+")
print("        +:.`oMNNN`                     .:-` `.::.` `--..---/+/---.```........-.:d:")
print("         ./++Ny::`                   `--`          .--..-----::-..```......---.s.")
print("           `:os.--`                  .`            `.. ``.------.`.```..-----.:o")
print("             `h-..`                 ``        .:syy/-/ydho-.--...`````.------.+.")
print("              +o`.`                        ./ymNNNNNNNmmNNNh:....``.```.-----:s")
print("              `h-`.                    -/+oyo/:----:---.--:+sso:........--::-+:")
print("               /d...                 `.++:  -:--/+:/oo+o++-.``--.....-----:-:y")
print("               `Md:.`                ``     `-:/+ooooo+/-........-----------yo")
print("                mNNs-`                     `..-/oo+://:/oo:......----------os")
print("                h:+md:.                  ...``.`         `------.---------++")
print("               `h..-+ddo.`                            ``.----------------s:")
print("                h` .--/ydy:`                   `...--------------------+y.")
print("                h`   ..--+yds+.`               `....----------------:+dN`")
print("               `y      `.-.-:sdhs:.`    `...````..----------------:smsdm")
print("               `h         .--..-+ymdy+/:----:----------------.-/shs+.`os")
print("               `h           `..--..:sdmmhyo/::----------::/+syhy/....`+-")
print("               -y              `..--..--/oosyyyhhhyyyssoooo/:.`...`.` /-")
print("               `.                  `..--.......................````   +`")
print("                                      `...------..-.........``")
print("                                          ``..-.--........``")
print("                                               ```..```")





